name: fo_components_example
description: Example showcasing fo_components
author: Patrick Minogue <patrick.minogue@gmail.com>
homepage: https://github.com/afpatmin/fo_components
version: 0.0.1
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.2.0  
  angular_forms: ^2.1.1
  angular_router: ^2.0.0-alpha+21  

  fo_components:
    path: '../'

  fo_model:
    git: https://github.com/afpatmin/fo_model
  
  grid:
    git: https://github.com/afpatmin/grid  

  sass_builder: ^2.1.2

dev_dependencies:
  build_runner: ^1.2.0
  build_web_compilers: ^1.2.0  