name: fo_components_demo
description: A web app that demoes fo_components
version: 0.0.1
#author: Patrick Minogue <patrick.minogue@gmail.com>

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^4.0.0
  angular_components: ^0.8.0
  fo_components:
    path: ../
  vi_auth_client:
    git: git://github.com/afpatmin/ViAuthClient

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  sass_builder: ^1.0.1

transformers:
- sass_builder:
    outputExtension: .css
- angular:
    entry_points:
      - web/main.dart

- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc
