name: fo_components
description: A collection of Angular Dart components
author: Patrick Minogue <patrick.minogue@gmail.com>
homepage: https://github.com/afpatmin
version: 0.0.1452
environment:
  sdk: '>=1.24.2 <2.0.0'

dependencies:
  angular: "^4.0.0-beta"
  angular_components: "^0.6.0-beta"
  vi_auth_client:
    path: ../ViAuthClient

transformers:
  - angular

#dev_dependencies:
