name: fo_components
description: A collection of Angular Dart components
author: Patrick Minogue <patrick.minogue@gmail.com>
homepage: https://github.com/afpatmin
version: 0.0.1452
environment:
  sdk: '>=1.24.2 <2.0.0'

dependencies:
  angular: "^4.0.0"
  angular_components: "^0.6.0"
  vi_auth_client:
    path: ../ViAuthClient

dev_dependencies:
  browser: ^0.10.0+2
  dart_to_js_script_rewriter: ^1.0.3


transformers:
- angular
- dart_to_js_script_rewriter