name: fo_components
description: A collection of Angular Dart components
author: Patrick Minogue <patrick.minogue@gmail.com>
homepage: https://github.com/afpatmin
version: 0.1.6
environment:
  sdk: '>=2.0.0-dev.61.0 <2.0.0'

dependencies:
  angular: 5.0.0-alpha+15
  angular_components: 0.9.0-alpha+15
  angular_forms: 2.0.0-alpha+7
  angular_router: ^2.0.0-alpha+14
  fo_model:
    git: https://github.com/afpatmin/fo_model.git
  grid:
    git: https://github.com/afpatmin/grid.git
  intl: ^0.15.6  
  vi_auth_client: ^0.1.1
  sass_builder: ^2.0.2
