name: fo_components
description: A collection of Angular Dart components
author: Patrick Minogue <patrick.minogue@gmail.com>
homepage: https://github.com/afpatmin
version: 0.1.2
environment:
  sdk: '>=1.24.2 <2.0.0'

dependencies:
  angular: "^4.0.0"
  angular_components: "^0.8.0"
  angular_router: "^1.0.2"
  grid:
    git: git://github.com/afpatmin/Grid
  vi_auth_client:
    git: git://github.com/afpatmin/ViAuthClient
  sass_builder: ^1.0.1

transformers:
- sass_builder:
    outputExtension: .scss.css
- angular