name: fo_components
description: A collection of Angular Dart components
author: Patrick Minogue <patrick.minogue@gmail.com>
homepage: https://github.com/afpatmin
version: 0.1.7
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.9.0
  angular_forms: ^2.0.0
  angular_router: ^2.0.0-alpha+19
  fo_model:
    git: https://github.com/afpatmin/fo_model.git
  grid:
    git: https://github.com/afpatmin/grid.git
  intl: ^0.15.7  
  vi_auth_client: ^0.1.3
  sass_builder: ^2.1.1

dev_dependencies:
  build_runner: ^0.10.0
